<a href="https://colab.research.google.com/github/JahnaviMandadi25/PythonForDataEngineering-Beginners2Advanced/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Array creation and attributes

In [1]:
import numpy as np  # Importing the NumPy library

nums = [1,2,3,4,5]  # Creating a list of numbers

arrayy1 = np.array(nums)  # Converting the list into a NumPy array
print(arrayy1)  # Printing the NumPy array


[1 2 3 4 5]


In [2]:
zero_array = np.zeros(5)  # Creating a NumPy array of zeros with 5 elements
print(zero_array)  # Printing the array


[0. 0. 0. 0. 0.]


In [3]:
one_array = np.ones(3)  # Creating a NumPy array of ones with 3 elements
print(one_array)  # Printing the array


[1. 1. 1.]


In [4]:
range_array = np.arange(1, 10, 2)  # Creating a NumPy array with values from 1 to 9 with a step of 2
print(range_array)  # Printing the array


[1 3 5 7 9]


In [6]:
random_array = np.random.randint(1, 100, 5)  # Creating a NumPy array with 5 random integers between 1 and 99
print(random_array)  # Printing the array


[47 10 77 17 79]


In [7]:
random_matrix = np.random.rand(3, 3)  # Creating a 3x3 matrix with random values between 0 and 1
print(random_matrix)  # Printing the matrix


[[0.01319309 0.74055904 0.72802547]
 [0.99704378 0.85307033 0.55071146]
 [0.8791649  0.72868317 0.14563978]]


In [8]:
shape = range_array.shape  # Getting the shape of the array
print(shape)  # Printing the shape (tuple representing dimensions)

(5,)


In [9]:
size = range_array.size  # Getting the total number of elements in the array
print(size)  # Printing the size

5


In [10]:
print(range_array.ndim)  # Printing the number of dimensions of the array

1


2. Array Operations

In [11]:
import numpy as np  # Importing the NumPy library

array1 = np.array([1, 2, 3])  # Creating an array
array2 = np.array([4, 5, 6])  # Creating another array

result = array1 + array2  # Adding the arrays element-wise
print(result)

[5 7 9]


In [12]:
sub = array1 - array2  # Subtracting the arrays element-wise
print(sub)

[-3 -3 -3]


In [13]:
mul = array1 * array2  # Multiplying the arrays element-wise
print(mul)

[ 4 10 18]


In [14]:
div = array1 / array2  # Dividing the arrays element-wise
print(div)

[0.25 0.4  0.5 ]


In [15]:
mean = np.mean(array1)  # Calculating the mean of the array
print(mean)

2.0


In [16]:
sum = np.sum(array1)  # Calculating the sum of the array
print(sum)

6


In [17]:
max = np.max(array1)  # Finding the maximum value in the array
print(max)

3


In [18]:
min = np.min(array1)  # Finding the minimum value in the array
print(min)

1


In [19]:
greater_than = array1 > 2 #Checking if every value in the array if greater than 2 or not

print(greater_than)

[False False  True]


In [20]:
result = array1 * 2  # Multiplying every value in the array by 2
print(result)

[2 4 6]


3. Indexing and Slicing


In [21]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])  # Creating a NumPy array with given elements

second_element = array1[1]  # Accessing the second element (index 1) of the array

print(second_element)  # Printing the second element


20


In [22]:
print(array1[-2])  # Printing the second-to-last element of the array (40)


40


In [23]:
sliced_arr = array1[1:4]  # Slicing the array from index 1 to 3 (excluding index 4)
print(sliced_arr)  # Printing the sliced array


[20 30 40]


In [24]:
step_arry = array1[::2]  # Slicing the array with a step of 2 (every second element)
print(step_arry)  # Printing the array with the step


[10 30 50]


In [25]:
matrix = np.array([[1, 2, 3],  # Creating a 3x3 matrix
                   [4, 5, 6],
                   [7, 8, 9]])

element = matrix[1, 1]  # Accessing the element at row 1, column 1 (which is 5)
print(element)  # Printing the accessed element


5


In [26]:
second_row = matrix[1, :]  # Accessing all elements in the second row of the matrix
print(second_row)  # Printing the second row


[4 5 6]


In [27]:
second_col = matrix[:, 1]  # Accessing all elements in the second column of the matrix
print(second_col)  # Printing the second column


[2 5 8]


In [28]:
data = np.array([1, 2, 3, np.nan, 4, 5])  # Creating an array with a NaN value

missing = np.isnan(data)  # Checking which elements are NaN (returns a boolean array)
print(missing)  # Printing the boolean array indicating missing (NaN) values


[False False False  True False False]


In [29]:
data_fill = np.nan_to_num(data, nan=100)  # Replacing NaN values in the array with 100
print(data_fill)  # Printing the array with NaN values replaced


[  1.   2.   3. 100.   4.   5.]


4. Linear algebra and statistics

In [30]:
import numpy as np  # Importing the NumPy library

array1 = np.array([[1, 2], [3, 4]])  # Creating a 2x2 array
array2 = np.array(([5, 6], [7, 8]))  # Creating another 2x2 array

mul = np.dot(array1, array2)  # Performing matrix multiplication (dot product) between array1 and array2

print(mul)  # Printing the result of the matrix multiplication


[[19 22]
 [43 50]]


In [31]:
invr = np.linalg.inv(array1)  # Calculating the inverse of the array1 matrix

print(invr)  # Printing the inverse of array1

[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
eval, evect = np.linalg.eig(array1)  # Calculating the eigenvalues and eigenvectors of the array1 matrix

print(eval)  # Printing the eigenvalues
print(evect)  # Printing the eigenvectors

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [33]:
data = np.array([1, 2, 3, 4, 5])  # Creating a NumPy array with data

mean = np.mean(data)  # Calculating the mean (average) of the data
median = np.median(data)  # Calculating the median of the data
std = np.std(data)  # Calculating the standard deviation of the data

print(mean)  # Printing the mean
print(median)  # Printing the median
print(std)  # Printing the standard deviation


3.0
3.0
1.4142135623730951
